// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_QIMU-LuiqWy8hbUJGCkEmmA56BIV-Ok',
    appId: '1:528400324708:web:dd20c0103310e1d68e2771',
    messagingSenderId: '528400324708',
    projectId: 'e-commerce-275ec',
    authDomain: 'e-commerce-275ec.firebaseapp.com',
    storageBucket: 'e-commerce-275ec.appspot.com',
    measurementId: 'G-RP6FBR2F9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR2P4DlcjObtErwObbHKd2KOR67tCT8rA',
    appId: '1:528400324708:android:6f194a02f4960dfd8e2771',
    messagingSenderId: '528400324708',
    projectId: 'e-commerce-275ec',
    storageBucket: 'e-commerce-275ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0djV4Emva2c4spTlmjaXFq7VqEJQXeO0',
    appId: '1:528400324708:ios:b57f999ae7fb37258e2771',
    messagingSenderId: '528400324708',
    projectId: 'e-commerce-275ec',
    storageBucket: 'e-commerce-275ec.appspot.com',
    iosClientId: '528400324708-d7lk1l5igo75f1k6jbhfqqrscmuetcen.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommersUser',
  );
}
